apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-currencies-app-backend
   # kubernetes.io/ingress.class: "nginx" 
   # ingress.alb.yc.io/external-ipv4-address: auto
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: currencies-app-backend
             port: 
                number: 5000



















