---
apiVersion: v1
kind: Service
metadata:
  name: currencies-app-backend
spec:
  ports:
  - port: 80
    name: plaintext
    targetPort: 5000
  selector:
    app: currencies-app-backend
  type: LoadBalancer



